<?php
/** Skin: Aurora · magenta→violet gradient · glow */
if ( ! defined( 'ABSPATH' ) ) exit;
?>
<nav class="mx-nav">
    <a class="mx-nav__brand" data-skin-link="home">⬢ on1.agency</a>
    <ul class="mx-nav__links"><li><a data-skin-link="home" class="is-active">Home</a></li><li><a data-skin-link="about">About</a></li><li><a data-skin-link="work">Case Studies</a></li><li><a data-skin-link="pricing">Services</a></li><li><a data-skin-link="faq">FAQ</a></li><li><a data-skin-link="contact">Contact</a></li></ul>
    <a class="mx-nav__cta" data-skin-link="contact">Book a Call →</a>
</nav>
<div data-skin-page="home" class="is-active">
    <header class="mx-hero"><div class="mx-aura"></div><p class="mx-tag">⚡ Experience the editorial advantage</p><h1 class="mx-hero__head">Revolutionizing<br><em>Digital Studios.</em></h1><p class="mx-hero__lede"><?php echo esc_html( $on1_content['lede'] ); ?></p><div class="mx-hero__buttons"><a class="mx-btn" data-skin-link="contact">Get Started →</a><a class="mx-btn mx-btn--ghost">Watch Demo ▷</a></div><div class="mx-hero__brands"><?php foreach ( $on1_content['work'] as $w ) echo '<span>' . esc_html( strtolower( explode( ' ', $w['title'] )[0] ) ) . '</span>'; ?></div></header>
    <section class="mx-stats"><div class="mx-stat"><span class="mx-stat__icon">✦</span><h3>14<em>+</em></h3><p>Sites Shipped</p></div><div class="mx-stat"><span class="mx-stat__icon">✦</span><h3>72<em>h</em></h3><p>Reply Window</p></div><div class="mx-stat"><span class="mx-stat__icon">✦</span><h3>4.9<em>/5</em></h3><p>Client Rating</p></div><div class="mx-stat"><span class="mx-stat__icon">✦</span><h3>1<em>:1</em></h3><p>Always</p></div></section>
    <section class="mx-quote"><p class="mx-tag">⚡ Take a Boost for Your Studio</p><h2 class="mx-section-head">Award-winning<br><em>editorial design.</em></h2><a class="mx-btn" data-skin-link="contact">Start a Brief →</a></section>
    <footer class="mx-foot"><h3 class="mx-foot__brand">⬢ on1.agency</h3><span>©2026 · Vienna · Booking Q3</span></footer>
</div>
<div data-skin-page="about"><header class="mx-hero"><div class="mx-aura"></div><p class="mx-tag">⚡ Founder · Solo Practice</p><h1 class="mx-hero__head">About the<br><em>Studio.</em></h1><p class="mx-hero__lede">Nishuthan Raveenthiran. One-person Vienna atelier since 2018.</p></header><section class="mx-stats"><?php foreach ( $on1_content['principles'] as $p ) : ?><div class="mx-stat"><span class="mx-stat__icon">✦</span><h3><?php echo esc_html( explode( ' ', $p[1] )[0] ); ?></h3><p><?php echo esc_html( $p[1] ); ?></p></div><?php endforeach; ?></section></div>
<div data-skin-page="work"><header class="mx-hero"><div class="mx-aura"></div><p class="mx-tag">⚡ 14 sites · since 2018</p><h1 class="mx-hero__head">Case<br><em>Studies.</em></h1></header><section class="mx-stats"><?php foreach ( array_slice( $on1_content['work'], 0, 4 ) as $w ) : ?><div class="mx-stat"><h3><?php echo esc_html( $w['title'] ); ?></h3><p><?php echo esc_html( $w['lede'] . ' · ' . $w['year'] ); ?></p></div><?php endforeach; ?></section></div>
<div data-skin-page="pricing"><header class="mx-hero"><div class="mx-aura"></div><p class="mx-tag">⚡ Three engagements</p><h1 class="mx-hero__head">Pricing<br><em>Tiers.</em></h1></header><section class="mx-stats"><?php $rom = [ 'i.', 'ii.', 'iii.' ]; foreach ( $on1_content['tiers'] as $i => $t ) : $f = ! empty( $t['featured'] ); ?><div class="mx-stat"<?php echo $f ? ' style="border-color:#FF4F92"' : ''; ?>><span class="mx-stat__icon"><?php echo esc_html( $rom[ $i ] ?? '·' ); ?></span><h3><?php echo esc_html( $t['price'] ); ?></h3><p><?php echo esc_html( $t['name'] . ' · ' . $t['sub'] ); ?></p></div><?php endforeach; ?></section></div>
<div data-skin-page="faq"><header class="mx-hero"><div class="mx-aura"></div><p class="mx-tag">⚡ Frequently asked</p><h1 class="mx-hero__head">Common<br><em>Questions.</em></h1></header><section class="mx-stats"><?php foreach ( array_slice( $on1_content['faq'], 0, 4 ) as $f ) : ?><div class="mx-stat"><h3 style="font-size:1.3rem"><?php echo esc_html( $f['q'] ); ?></h3><p><?php echo esc_html( $f['a'] ); ?></p></div><?php endforeach; ?></section></div>
<div data-skin-page="contact"><header class="mx-hero"><div class="mx-aura"></div><p class="mx-tag">⚡ Send a brief · 72h reply</p><h1 class="mx-hero__head">Get in<br><em>Touch.</em></h1></header><section class="mx-stats"><div class="mx-stat"><span class="mx-stat__icon">@</span><h3 style="font-size:1.3rem"><?php echo esc_html( $on1_content['identity']['email'] ); ?></h3><p>Email us</p></div><div class="mx-stat"><span class="mx-stat__icon">📍</span><h3 style="font-size:1.3rem">Wien</h3><p>UTC+1</p></div><div class="mx-stat"><span class="mx-stat__icon">⏱</span><h3 style="font-size:1.3rem">72h</h3><p>Response</p></div><div class="mx-stat"><span class="mx-stat__icon">⚡</span><h3 style="font-size:1.3rem">Q3</h3><p>Booking open</p></div></section></div>
