<?php
/** Skin: Salon · light cream + hot pink · serif italic */
if ( ! defined( 'ABSPATH' ) ) exit;
?>
<nav class="rv-nav">
    <a class="rv-nav__brand" data-skin-link="home">on1.</a>
    <ul class="rv-nav__links"><li><a data-skin-link="home" class="is-active">home</a></li><li><a data-skin-link="about">about</a></li><li><a data-skin-link="work">projects</a></li><li><a data-skin-link="pricing">pricing</a></li><li><a data-skin-link="faq">faq</a></li><li><a data-skin-link="contact">contact</a></li></ul>
    <a class="rv-nav__cta" data-skin-link="contact">let's talk ↗</a>
</nav>
<div data-skin-page="home" class="is-active">
    <header class="rv-hero"><p class="rv-tag">start project</p><h1 class="rv-hero__head"><span class="rv-faint">where strategy</span><br>meets <em>creativity</em></h1>
        <div class="rv-hero__stats"><div><strong>14+</strong><span>shipped projects</span></div><div><strong>50+</strong><span>happy clients</span></div><div><strong>72h</strong><span>reply window</span></div></div>
        <div class="rv-hero__card"><p class="rv-faint">about us</p><p><?php echo esc_html( $on1_content['lede'] ); ?></p><div class="rv-rating">★★★★★ <strong>4.9</strong> <span class="rv-faint">average rating from 500+ clients</span></div><a class="rv-pink-btn" data-skin-link="about">learn more</a></div>
    </header>
    <section class="rv-services"><span class="rv-faint">what we do</span><h2 class="rv-section-head">Empowering studios to grow online.</h2><div class="rv-service-grid"><?php foreach ( $on1_content['services'] as $s ) : ?><div class="rv-service"><span class="rv-arrow">↗</span><h3><?php echo esc_html( strtolower( $s['name'] ) ); ?>.</h3><p class="rv-faint"><?php echo esc_html( $s['lede'] ); ?></p></div><?php endforeach; ?></div></section>
    <section class="rv-cta"><h2>talk to us.<br>let's unlock <em>your digital potential.</em></h2><a class="rv-pink-btn rv-pink-btn--lg" data-skin-link="contact">submit ↗</a></section>
    <footer class="rv-foot"><h3 class="rv-foot__brand">on1.</h3><p>©2026 on1.agency · all rights reserved.</p></footer>
</div>
<div data-skin-page="about"><header class="rv-hero"><p class="rv-tag">founder</p><h1 class="rv-hero__head"><span class="rv-faint">about</span><br>nishuthan <em>raveenthiran</em></h1><div class="rv-hero__card"><p class="rv-faint">studio</p><p>A one-person Vienna atelier since 2018. Eight years building editorial WordPress sites and design systems.</p></div></header><section class="rv-services"><span class="rv-faint">principles</span><h2 class="rv-section-head">Four working <em>principles</em>.</h2><div class="rv-service-grid"><?php foreach ( $on1_content['principles'] as $p ) : ?><div class="rv-service"><span class="rv-arrow">↗</span><h3><?php echo esc_html( strtolower( explode( ' ', $p[1] )[0] ) ); ?>.</h3><p class="rv-faint"><?php echo esc_html( $p[1] ); ?></p></div><?php endforeach; ?></div></section></div>
<div data-skin-page="work"><header class="rv-hero"><p class="rv-tag">portfolio</p><h1 class="rv-hero__head"><span class="rv-faint">recent</span><br><em>projects.</em></h1></header><section class="rv-services"><div class="rv-service-grid"><?php foreach ( $on1_content['work'] as $w ) : ?><div class="rv-service"><span class="rv-arrow">↗</span><h3><?php echo esc_html( $w['title'] ); ?><br><span class="rv-faint" style="font-size:0.6em"><?php echo esc_html( $w['year'] ); ?></span></h3><p class="rv-faint"><?php echo esc_html( $w['lede'] ); ?></p></div><?php endforeach; ?></div></section></div>
<div data-skin-page="pricing"><header class="rv-hero"><p class="rv-tag">pricing</p><h1 class="rv-hero__head"><span class="rv-faint">three</span><br><em>engagements.</em></h1></header><section class="rv-services"><div class="rv-service-grid" style="grid-template-columns:repeat(3,1fr)"><?php foreach ( $on1_content['tiers'] as $t ) : $f = ! empty( $t['featured'] ); ?><div class="rv-service"<?php echo $f ? ' style="background:#0F0F12;color:#fff;padding:1.5rem;border-radius:14px"' : ''; ?>><h3<?php echo $f ? ' style="color:#fff"' : ''; ?>><?php echo esc_html( strtolower( $t['name'] ) ); ?>.<br><span style="color:#FF1F8C"><?php echo esc_html( $t['price'] ); ?></span></h3><p class="rv-faint"<?php echo $f ? ' style="color:rgba(255,255,255,0.6)"' : ''; ?>><?php echo esc_html( $t['sub'] ); ?></p></div><?php endforeach; ?></div></section></div>
<div data-skin-page="faq"><header class="rv-hero"><p class="rv-tag">faq</p><h1 class="rv-hero__head"><span class="rv-faint">common</span><br><em>questions.</em></h1></header><section class="rv-services"><div class="rv-service-grid"><?php foreach ( $on1_content['faq'] as $f ) : ?><div class="rv-service"><h3><?php echo esc_html( strtolower( $f['q'] ) ); ?></h3><p class="rv-faint"><?php echo esc_html( $f['a'] ); ?></p></div><?php endforeach; ?></div></section></div>
<div data-skin-page="contact"><header class="rv-hero"><p class="rv-tag">contact</p><h1 class="rv-hero__head"><span class="rv-faint">send a</span><br><em>brief.</em></h1></header><section class="rv-cta" style="border-radius:24px"><h2>let's unlock your <em>digital potential</em></h2><div class="rv-service-grid" style="grid-template-columns:repeat(4,1fr);max-width:900px;margin:2rem auto 0"><div><strong>@</strong><br><span class="rv-faint"><?php echo esc_html( $on1_content['identity']['email'] ); ?></span></div><div><strong>📍</strong><br><span class="rv-faint">wien · utc+1</span></div><div><strong>⏱</strong><br><span class="rv-faint">72h response</span></div><div><strong>⚡</strong><br><span class="rv-faint">q3 slots open</span></div></div></section></div>
